- hosts: all
  become: yes
  roles:
    - install-openjdk
  tasks:
    - name: Run integration tests of Spark with k8s cluster manager
      shell: |

        sed -i -e '/127.0.0.1/ s/\(localhost\)/'$(hostname)' \1/' /etc/hosts
        echo '{{ zuul.project.src_dir }}'
        # install and start microk8s
        sudo apt update
        sudo apt install snapd -y
        sudo snap install microk8s --classic
        snap info microk8s
        sudo microk8s.start
        snap alias microk8s.kubectl kubectl
        
        sleep 36000
        export DATE=`date "+%Y%m%d"`
        export REVISION=`git rev-parse --short HEAD`
        export ZINC_PORT=$(python -S -c "import random; print random.randrange(3030,4030)")
  
        ./dev/make-distribution.sh --name ${DATE}-${REVISION} --pip --tgz -DzincPort=${ZINC_PORT} \
             -Phadoop-2.7 -Pkubernetes -Pkinesis-asl -Phive -Phive-thriftserver
  
        sudo kubectl create clusterrolebinding serviceaccounts-cluster-admin --clusterrole=cluster-admin --group=system:serviceaccounts || true
  
        ./resource-managers/kubernetes/integration-tests/dev/dev-run-integration-tests.sh \
            --spark-master k8s://$(sudo kubectl config view -o jsonpath='{.clusters[0].cluster.server}') \
            --deploy-mode cloud --spark-tgz {{ ansible_user_dir }}/{{ zuul.project.src_dir }}/spark-*.tgz
      args:
        executable: /bin/bash
        chdir: '{{ zuul.project.src_dir }}'
      environment: '{{ global_env }}'
